ARG BASE_IMAGE=ubuntu:24.04
ARG VALIDATE_IMAGE=ubuntu:24.04
ARG VALIDATE=true

FROM golang AS build
ARG TARGETARCH
ENV SKIP_UPX=true
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /app
COPY Makefile .
RUN make all
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
RUN go build -o /app/kairos-init .


FROM scratch AS kairos-init
COPY --from=build /app/kairos-init /kairos-init

# Target to use the validator directly inside a generated image with kairos-init
FROM ${VALIDATE_IMAGE} AS validate
COPY --from=build /app/kairos-init /kairos-init
RUN /kairos-init validate

FROM ${BASE_IMAGE} AS default
ARG MODEL=generic
ARG TRUSTED_BOOT=false
ARG PROVIDER_NAME
ARG PROVIDER_VERSION
ARG VERSION=v0.0.1
ARG FIPS=false
ARG VALIDATE

COPY --from=kairos-init /kairos-init /kairos-init
RUN /kairos-init -l debug -m "${MODEL}" -t "${TRUSTED_BOOT}" --provider "${PROVIDER_NAME}" --provider-"${PROVIDER_NAME}"-version "${PROVIDER_VERSION}" --version "${VERSION}" "$(if [ "${FIPS}" = "true" ]; then echo "--fips"; fi)"
RUN if [ "${VALIDATE}" = 'true' ];then /kairos-init validate -t "${TRUSTED_BOOT}"; fi
RUN rm /kairos-init