name: "Kubeadm Provider Configuration"
stages:
  boot:
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      only_service_manager: "systemd"
      files:
        - path: /etc/kubernetes/kubeadm-config.yaml
          permissions: 0644
          owner: 0
          group: 0
          content: |
            apiVersion: kubeadm.k8s.io/v1beta3
            kind: InitConfiguration
            nodeRegistration:
              criSocket: "unix:///var/run/containerd/containerd.sock"
            ---
            apiVersion: kubeadm.k8s.io/v1beta3
            kind: ClusterConfiguration
            kubernetesVersion: "v1.28.0"
            networking:
              podSubnet: "10.244.0.0/16"
            apiServer:
              extraArgs:
                cloud-provider: "external"
        - path: /etc/kubernetes/kubeadm-join-config.yaml
          permissions: 0644
          owner: 0
          group: 0
          content: |
            apiVersion: kubeadm.k8s.io/v1beta3
            kind: JoinConfiguration
            nodeRegistration:
              criSocket: "unix:///var/run/containerd/containerd.sock"
            discovery:
              bootstrapToken:
                apiServerEndpoint: "{{ .KubeadmAPIServerEndpoint }}"
                token: "{{ .KubeadmToken }}"
                caCertHashes:
                - "{{ .KubeadmCACertHash }}"
  initramfs:
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      only_service_manager: "systemd"
      files:
        - path: /etc/kubernetes/kubeadm-config.yaml
          permissions: 0644
          owner: 0
          group: 0
          content: |
            apiVersion: kubeadm.k8s.io/v1beta3
            kind: InitConfiguration
            nodeRegistration:
              criSocket: "unix:///var/run/containerd/containerd.sock"
            ---
            apiVersion: kubeadm.k8s.io/v1beta3
            kind: ClusterConfiguration
            kubernetesVersion: "v1.28.0"
            networking:
              podSubnet: "10.244.0.0/16"
            apiServer:
              extraArgs:
                cloud-provider: "external" 