name: Docker image build

on:
  pull_request: 
  push:
    branches:
      - 'main'

concurrency:
  group: build-main-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  dockerImages:
    runs-on: ${{ matrix.platform && matrix.platform == 'amd64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    name: Docker image ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ "amd64", "arm64" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.platform}}
          push: true
          tags: ttl.sh/kairos-${{ matrix.platform }}:${{ github.sha }}