name: security.yml
on:
  pull_request:
  push:
    branches:
      - main


permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents and actions
  contents: read
  actions: read

jobs:
  ovs-scan:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@2a387edfbe02a11d856b89172f6e978100177eb4" # v2.3.2
  grype-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download bundled binaries
        run: |
          make download
        env:
          SKIP_UPX: true
      - name: Run Grype security scan
        uses: anchore/scan-action@1638637db639e0ade3258b51db49a9a137574c3e # v6.5.1
        with:
          path: ./pkg/bundled/binaries
          output-format: json
          severity-cutoff: critical
          add-cpes-if-none: true
          only-fixed: true
          fail-build: false